language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules


before_install:
  - npm install

scripts:

  - "./node_modules/.bin/jsHint"
  - "./node_modules/.bin/retire"
  - "./node_modules/.bin/twly"
